Implementing statistics
AgueroMishel/transactions pull request #1
Opened 2020-03-03 06:19 UTC by AgueroMishel

2020-03-03 15:49 UTC, wombstrat requested changes
i'd like to see this passing the ITests

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsController.java
> +public class TransactionsController {
Is it needed to make this controller public?, if so, why?

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsHandler.java
> +public class TransactionsHandler {
why did you choose between component and not `@Service`

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsHandler.java
> +    private static int nextKey = 0;
What's the standard for constants in java?

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsHandler.java
> +        instance = new TransactionsHandler();
if this project's using spring, wouldn't be better injecting it by constructor?

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsHandler.java
> +    public synchronized void createStatistics() {
why synchronized here?

2020-03-03 15:49 UTC, wombstrat commented on src/main/java/org/app/TransactionsHandler.java
> +        for(Map.Entry<Integer,Transaction> currentEntry : storage.entrySet()) {
What's the complexity of this code?

2020-04-03 18:37 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsHandler.java
> +public class TransactionsHandler {
![Annotation](https://user-images.githubusercontent.com/30968547/78393744-a8311a80-75a7-11ea-8830-f4401699722d.png)

According what we discuss. It's about context. So, I will change this to `@Service`

2020-04-03 18:40 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsController.java
> +public class TransactionsController {
Making this `default package`, that way only classes in the same package will have access to this class. (Is not possible to do it `private`)

2020-04-03 18:48 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsHandler.java
> +        for(Map.Entry<Integer,Transaction> currentEntry : storage.entrySet()) {
Linear Time: O(n)

2020-04-03 18:49 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsHandler.java
> +    private static int nextKey = 0;
According what we discuss. Those are not constants, are `static member variables`, that's why they are in LOWER CASE instead of UPPER CASE

2020-04-03 18:53 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsHandler.java
> +        instance = new TransactionsHandler();
I'm trying to make sure that only and ONLY ONE instance of this it's being created.

2020-04-03 18:56 UTC, AgueroMishel commented on src/main/java/org/app/TransactionsHandler.java
> +    public synchronized void createStatistics() {
Since it is working with `statistics`, I'm trying to prevent a deadlock

2020-04-03 18:58 UTC, merged